var searchData=
[
  ['readme_44',['README',['../md_data_result_test22aretes_g9__r_e_a_d_m_e.html',1,'']]],
  ['readme_2emd_45',['README.md',['../data_2result_2test22aretes__g9_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../_r_e_a_d_m_e_8md.html',1,'(Global Namespace)']]],
  ['recursivesubgraphs_46',['recursiveSubgraphs',['../cycle_count_8h.html#a84eabb4f4c460f175ec21b366b5efd63',1,'recursiveSubgraphs(std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, unsigned long length, std::vector&lt; int &gt; subgraph, std::vector&lt; bool &gt; allowedVertex, std::vector&lt; double &gt; primes, std::vector&lt; bool &gt; neighbourhood, bool directed):&#160;cycleCount.cpp'],['../cycle_count_8cpp.html#a84eabb4f4c460f175ec21b366b5efd63',1,'recursiveSubgraphs(std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, unsigned long length, std::vector&lt; int &gt; subgraph, std::vector&lt; bool &gt; allowedVertex, std::vector&lt; double &gt; primes, std::vector&lt; bool &gt; neighbourhood, bool directed):&#160;cycleCount.cpp']]],
  ['recursivesubgraphsfixedvertex_47',['recursiveSubgraphsFixedVertex',['../cycle_count_8h.html#ae7cadb51183f7418039b7a59e0e1c291',1,'recursiveSubgraphsFixedVertex(std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, int vertex, unsigned long length, std::vector&lt; int &gt; subgraph, std::vector&lt; bool &gt; allowedVertex, std::vector&lt; double &gt; primes, std::vector&lt; bool &gt; neighbourhood):&#160;cycleCount.cpp'],['../cycle_count_8cpp.html#ae7cadb51183f7418039b7a59e0e1c291',1,'recursiveSubgraphsFixedVertex(std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, int vertex, unsigned long length, std::vector&lt; int &gt; subgraph, std::vector&lt; bool &gt; allowedVertex, std::vector&lt; double &gt; primes, std::vector&lt; bool &gt; neighbourhood):&#160;cycleCount.cpp']]],
  ['recursivesubgraphspaths_48',['recursiveSubgraphsPaths',['../cycle_count_8h.html#ad27cf7494f9faa660df78fbd19af5cb3',1,'recursiveSubgraphsPaths(std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, unsigned long length, std::vector&lt; int &gt; subgraph, std::vector&lt; bool &gt; allowedVertex, std::vector&lt; std::vector&lt; std::vector&lt; double &gt;&gt;&gt; &amp;primes, std::vector&lt; bool &gt; neighbourhood, bool directed):&#160;cycleCount.cpp'],['../cycle_count_8cpp.html#ad27cf7494f9faa660df78fbd19af5cb3',1,'recursiveSubgraphsPaths(std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, unsigned long length, std::vector&lt; int &gt; subgraph, std::vector&lt; bool &gt; allowedVertex, std::vector&lt; std::vector&lt; std::vector&lt; double &gt;&gt;&gt; &amp;primes, std::vector&lt; bool &gt; neighbourhood, bool directed):&#160;cycleCount.cpp']]],
  ['restrictedadjacencymatrix_49',['restrictedAdjacencyMatrix',['../cycle_count_8h.html#acca0046271d64973dba4093a67e1a904',1,'restrictedAdjacencyMatrix(const std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, const std::vector&lt; int &gt; &amp;subgraph):&#160;cycleCount.cpp'],['../cycle_count_8cpp.html#acca0046271d64973dba4093a67e1a904',1,'restrictedAdjacencyMatrix(const std::vector&lt; std::vector&lt; double &gt;&gt; &amp;adjacencyMatrix, const std::vector&lt; int &gt; &amp;subgraph):&#160;cycleCount.cpp']]]
];
